version: '3.2'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/data/db
  app:
    image: node:18
    container_name: duff_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
